---

- name: "offline {{app}} from consul"
  uri:
    url: "http://{{consul}}/v1/kv/upstreams/{{service}}/{{ansible_ssh_host}}:{{httpport}}?token={{token}}"
    method: PUT
    body: '{"weight": {{weight | to_json}}, "max_fails":2, "fail_timeout":10, "down":1}'
    status_code: 200, 201
  connection: local

- name: "offline cas from consul"
  uri:
    url: "http://{{consul}}/v1/kv/upstreams/cas/{{ansible_ssh_host}}:{{httpport}}?token={{token}}"
    method: PUT
    body: '{"weight": {{weight | to_json}}, "max_fails":2, "fail_timeout":10, "down":1}'
    status_code: 200, 201
  connection: local
  when: service == 'tutor'

- name: "offline sx from consul"
  uri:
    url: "http://{{consul}}/v1/kv/upstreams/sx/{{ansible_ssh_host}}:{{httpport}}?token={{token}}"
    method: PUT
    body: '{"weight": {{weight | to_json}}, "max_fails":2, "fail_timeout":10, "down":1}'
    status_code: 200, 201
  connection: local
  when: service == 'eduplan'
